language: java
jdk:
  - oraclejdk8
install : mvn package

deploy:
  provider: heroku
  api_key:
    secure: csxS4cuCYq6Ou848tdBXrw+T3NSW2oY4zX85Ow7pNsqaNKU5QQo23epjEfNdlm/dnEz1z/lG97TYkhyP2N3owHc2X/0y2VldRBN8MVWmpDa+cr3jt1yHnKCNuCfs6B1SuO7+YkAT02nHJLczRiOBcVxHVJStcEABP10k15YTL8h2y82EiMSmo8akWSQUyOBd5w1beS1x0jX/YXzwhPV+pVfkx5PGfF3fi2af1Ly3kJzTHivdO/YxCnJeVR9R/YkbpgiIeiXR3xwqvLf94zzTRDhXTkjgYe7TPGciRNx5668eZrjs5LpDPAvKNcx6DcLSfOlZUmIZpYMuDsm3lcsJDkuyH9aMLrih6q5M/YLn7u59kXLRGXbTwz2U2HhalkMI71CaS6vMOlnBCKXWAaFrgxChETrlO6F/d4nng7INNlwuAQBL/BpYPmPESoS+ftgLIsVdHMz1KQekWvlfRVCsxShlhdi5OOjPYH7W+QyyGI4PAOPPbx6ofA0t064lYHV2Fj0vNXA8o1iXwYBceqEGxnh1UIzyawMTYoxpdkArzHWEXFM10dHqNrGlsJBuf1oh8Li6nqCgGxyrGkaVmV7e0gKFEwVEfijPCWgoEjbrymHLIYs0K4M18mT95yIMkIo4Z5XSHok8AyaOHtENoTzuxyLFGS922oTCra+jYbzAYcw=
  app: nameless-sierra-10830
  on:
    repo: nicolasMachut/JobSearchProject
