language: java
jdk:
  - oraclejdk8
install : mvn package

deploy:
  provider: heroku
  api_key:
    secure: ce9db6ea-67fc-45ea-9d8e-a9702e9f72f2
  app: nameless-sierra-10830
  on:
    repo: nicolasMachut/JobSearchProject
